package auth

import (
	"context"
	"database/sql"
	"errors"
	"time"
)

type User struct {
	ID          string
	Username    string
	Role        string
	DisplayName string
}

type Session struct {
	TokenHash  string
	UserID     string
	CreatedAt  time.Time
	LastUsedAt time.Time
	ExpiresAt  time.Time
}

var ErrInvalidSession = errors.New("invalid session")

// CreateSession inserts a session row for the user with the given TTL.
// The raw token is generated by the caller via NewToken().
func CreateSession(ctx context.Context, db *sql.DB, userID, tokenHash, userAgent, ip string, ttl time.Duration) error {
	now := time.Now().Unix()
	exp := time.Now().Add(ttl).Unix()
	_, err := db.ExecContext(ctx, `
		INSERT INTO sessions (token_hash, user_id, created_at, last_used_at, expires_at, user_agent, ip)
		VALUES (?, ?, ?, ?, ?, ?, ?)`,
		tokenHash, userID, now, now, exp, userAgent, ip)
	return err
}

// LookupSession validates a bearer token, returning the associated user.
// Updates last_used_at as a side effect on hit.
func LookupSession(ctx context.Context, db *sql.DB, tokenHash string) (*User, error) {
	now := time.Now().Unix()
	var u User
	var disabledAt sql.NullInt64
	err := db.QueryRowContext(ctx, `
		SELECT u.id, u.username, u.role, u.display_name, u.disabled_at
		FROM sessions s
		JOIN users u ON u.id = s.user_id
		WHERE s.token_hash = ? AND s.expires_at > ?`,
		tokenHash, now,
	).Scan(&u.ID, &u.Username, &u.Role, &u.DisplayName, &disabledAt)
	if errors.Is(err, sql.ErrNoRows) {
		return nil, ErrInvalidSession
	}
	if err != nil {
		return nil, err
	}
	if disabledAt.Valid {
		return nil, ErrInvalidSession
	}
	_, _ = db.ExecContext(ctx, `UPDATE sessions SET last_used_at = ? WHERE token_hash = ?`, now, tokenHash)
	return &u, nil
}

func DeleteSession(ctx context.Context, db *sql.DB, tokenHash string) error {
	_, err := db.ExecContext(ctx, `DELETE FROM sessions WHERE token_hash = ?`, tokenHash)
	return err
}

func DeleteUserSessions(ctx context.Context, db *sql.DB, userID string) error {
	_, err := db.ExecContext(ctx, `DELETE FROM sessions WHERE user_id = ?`, userID)
	return err
}

// GCSessions deletes expired sessions; safe to call from a periodic job.
func GCSessions(ctx context.Context, db *sql.DB) (int64, error) {
	res, err := db.ExecContext(ctx, `DELETE FROM sessions WHERE expires_at <= ?`, time.Now().Unix())
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}
